import React from 'react'
import './footer.css'

const Footer = () => {
  return (
    <div><h3>asdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasgasdgdasgdgasdgsadasg</h3></div>
  )
}

export default Footer